# ---------------------------------------------------------------
# Jekyll & Global Configuration
## Docs: https://jekyllrb.com/docs/configuration/
# ---------------------------------------------------------------

# Site
title: NexT
subtitle:
description:
author: SnoWolf2018
# Support language: de, en, fr-FR, id, ja, ko, pt-BR, pt, ru, zh-Hans, zh-hk, zh-tw
language: zh-Hans
date_format: '%Y-%m-%d'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com' and baseurl as '/child'
url:
baseurl: 'https://snowolf2018.github.io'
permalink: pretty

# Pagination
paginate: 10
#paginate_path: "/page:num/"
#archive:
  #paginate: 10
  #paginate_path: "/page:num/"
#category:
  #paginate: 10
  #paginate_path: "/page:num/"
#tag:
  #paginate: 10
  #paginate_path: "/page:num/"

# Hand
